#############################################################################
# Makefile for building: bin/yeroth-erp-3-0-system-daemon
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  yeroth-erp-3-0-system-daemon.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile yeroth-erp-3-0-system-daemon.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Imoc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = yeroth-erp-3-0-system-daemon3.0
DISTDIR = /home/yerith/yeroth-erp-3-0-system-daemon/obj/yeroth-erp-3-0-system-daemon3.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5DBus.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/YRruntimeverification_adaptor.cpp \
		src/IYRruntimeverificationAdaptor_interface.cpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.cpp \
		src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.cpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.cpp \
		src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.cpp \
		src/yeroth-erp-3-0-system-daemon.cpp \
		src/utils/yeroth-erp-database-table-column.cpp \
		src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp \
		src/yeroth-erp-3-0-system-daemon-periode.cpp \
		src/yeroth-erp-3-0-system-daemon-database.cpp \
		src/yeroth-erp-3-0-system-daemon-quantite.cpp \
		src/yeroth-erp-3-0-system-daemon-logger.cpp \
		src/yeroth-erp-3-0-system-daemon-config.cpp moc/moc_YRruntimeverification_adaptor.cpp \
		moc/moc_IYRruntimeverificationAdaptor_interface.cpp \
		moc/moc_YEROTH_RUNTIME_VERIFIER.cpp \
		moc/moc_yeroth-erp-3-0-system-daemon-abstract-entity.cpp \
		moc/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp \
		moc/moc_yeroth-erp-3-0-system-daemon-utils.cpp \
		moc/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp \
		moc/moc_yeroth-erp-3-0-system-daemon-periode.cpp \
		moc/moc_yeroth-erp-3-0-system-daemon-quantite.cpp
OBJECTS       = obj/YRruntimeverification_adaptor.o \
		obj/IYRruntimeverificationAdaptor_interface.o \
		obj/YEROTH_RUNTIME_VERIFIER.o \
		obj/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.o \
		obj/yeroth-erp-3-0-system-daemon-abstract-entity.o \
		obj/yeroth-erp-3-0-system-daemon-alert-abstract-entity.o \
		obj/yeroth-erp-3-0-system-daemon-utils.o \
		obj/yeroth-erp-3-0-system-daemon.o \
		obj/yeroth-erp-database-table-column.o \
		obj/yeroth-erp-3-0-system-daemon-db-backup-export-gz.o \
		obj/yeroth-erp-3-0-system-daemon-periode.o \
		obj/yeroth-erp-3-0-system-daemon-database.o \
		obj/yeroth-erp-3-0-system-daemon-quantite.o \
		obj/yeroth-erp-3-0-system-daemon-logger.o \
		obj/yeroth-erp-3-0-system-daemon-config.o \
		obj/moc_YRruntimeverification_adaptor.o \
		obj/moc_IYRruntimeverificationAdaptor_interface.o \
		obj/moc_YEROTH_RUNTIME_VERIFIER.o \
		obj/moc_yeroth-erp-3-0-system-daemon-abstract-entity.o \
		obj/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.o \
		obj/moc_yeroth-erp-3-0-system-daemon-utils.o \
		obj/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.o \
		obj/moc_yeroth-erp-3-0-system-daemon-periode.o \
		obj/moc_yeroth-erp-3-0-system-daemon-quantite.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		yeroth-erp-3-0-system-daemon.pro src/YRruntimeverification_adaptor.h \
		src/IYRruntimeverificationAdaptor_interface.h \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/include/yeroth-erp-3-0-software-text-configuration.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/utils/yeroth-erp-database-table-column.hpp \
		src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.hpp \
		src/yeroth-erp-3-0-system-daemon-periode.hpp \
		src/yeroth-erp-3-0-system-daemon-database.hpp \
		src/yeroth-erp-3-0-system-daemon-quantite.hpp \
		src/yeroth-erp-3-0-system-daemon-logger.hpp \
		src/yeroth-erp-3-0-system-daemon-config.hpp src/YRruntimeverification_adaptor.cpp \
		src/IYRruntimeverificationAdaptor_interface.cpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.cpp \
		src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.cpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.cpp \
		src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.cpp \
		src/yeroth-erp-3-0-system-daemon.cpp \
		src/utils/yeroth-erp-database-table-column.cpp \
		src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp \
		src/yeroth-erp-3-0-system-daemon-periode.cpp \
		src/yeroth-erp-3-0-system-daemon-database.cpp \
		src/yeroth-erp-3-0-system-daemon-quantite.cpp \
		src/yeroth-erp-3-0-system-daemon-logger.cpp \
		src/yeroth-erp-3-0-system-daemon-config.cpp
QMAKE_TARGET  = yeroth-erp-3-0-system-daemon
DESTDIR       = bin/
TARGET        = bin/yeroth-erp-3-0-system-daemon


first: all
####### Build rules

bin/yeroth-erp-3-0-system-daemon:  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: yeroth-erp-3-0-system-daemon.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		yeroth-erp-3-0-system-daemon.pro
	$(QMAKE) -o Makefile yeroth-erp-3-0-system-daemon.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
yeroth-erp-3-0-system-daemon.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile yeroth-erp-3-0-system-daemon.pro

qmake_all: FORCE


all: Makefile bin/yeroth-erp-3-0-system-daemon

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/YRruntimeverification_adaptor.h src/IYRruntimeverificationAdaptor_interface.h src/dbus/YEROTH_RUNTIME_VERIFIER.hpp src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.hpp src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp src/include/yeroth-erp-3-0-software-text-configuration.hpp src/utils/yeroth-erp-3-0-system-daemon-utils.hpp src/utils/yeroth-erp-database-table-column.hpp src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.hpp src/yeroth-erp-3-0-system-daemon-periode.hpp src/yeroth-erp-3-0-system-daemon-database.hpp src/yeroth-erp-3-0-system-daemon-quantite.hpp src/yeroth-erp-3-0-system-daemon-logger.hpp src/yeroth-erp-3-0-system-daemon-config.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/YRruntimeverification_adaptor.cpp src/IYRruntimeverificationAdaptor_interface.cpp src/dbus/YEROTH_RUNTIME_VERIFIER.cpp src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.cpp src/include/yeroth-erp-3-0-system-daemon-abstract-entity.cpp src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp src/utils/yeroth-erp-3-0-system-daemon-utils.cpp src/yeroth-erp-3-0-system-daemon.cpp src/utils/yeroth-erp-database-table-column.cpp src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp src/yeroth-erp-3-0-system-daemon-periode.cpp src/yeroth-erp-3-0-system-daemon-database.cpp src/yeroth-erp-3-0-system-daemon-quantite.cpp src/yeroth-erp-3-0-system-daemon-logger.cpp src/yeroth-erp-3-0-system-daemon-config.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) obj/yeroth-erp-3-0-system-daemon.gch/c obj/yeroth-erp-3-0-system-daemon.gch/c++
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

###### Precompiled headers
obj/yeroth-erp-3-0-system-daemon.gch/c: src/include/yeroth-erp-3-0-precompiled-header.hpp 
	@test -d obj/yeroth-erp-3-0-system-daemon.gch/ || mkdir -p obj/yeroth-erp-3-0-system-daemon.gch/
	$(CC) $(CFLAGS) $(INCPATH) -x c-header -c src/include/yeroth-erp-3-0-precompiled-header.hpp -o obj/yeroth-erp-3-0-system-daemon.gch/c

obj/yeroth-erp-3-0-system-daemon.gch/c++: src/include/yeroth-erp-3-0-precompiled-header.hpp 
	@test -d obj/yeroth-erp-3-0-system-daemon.gch/ || mkdir -p obj/yeroth-erp-3-0-system-daemon.gch/
	$(CXX) $(CXXFLAGS) $(INCPATH) -x c++-header -c src/include/yeroth-erp-3-0-precompiled-header.hpp -o obj/yeroth-erp-3-0-system-daemon.gch/c++

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	g++ -pipe -dM -E -o moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_YRruntimeverification_adaptor.cpp moc/moc_IYRruntimeverificationAdaptor_interface.cpp moc/moc_YEROTH_RUNTIME_VERIFIER.cpp moc/moc_yeroth-erp-3-0-system-daemon-abstract-entity.cpp moc/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp moc/moc_yeroth-erp-3-0-system-daemon-utils.cpp moc/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp moc/moc_yeroth-erp-3-0-system-daemon-periode.cpp moc/moc_yeroth-erp-3-0-system-daemon-quantite.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_YRruntimeverification_adaptor.cpp moc/moc_IYRruntimeverificationAdaptor_interface.cpp moc/moc_YEROTH_RUNTIME_VERIFIER.cpp moc/moc_yeroth-erp-3-0-system-daemon-abstract-entity.cpp moc/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp moc/moc_yeroth-erp-3-0-system-daemon-utils.cpp moc/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp moc/moc_yeroth-erp-3-0-system-daemon-periode.cpp moc/moc_yeroth-erp-3-0-system-daemon-quantite.cpp
moc/moc_YRruntimeverification_adaptor.cpp: src/YRruntimeverification_adaptor.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yerith/yeroth-erp-3-0-system-daemon/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yerith/yeroth-erp-3-0-system-daemon -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/YRruntimeverification_adaptor.h -o moc/moc_YRruntimeverification_adaptor.cpp

moc/moc_IYRruntimeverificationAdaptor_interface.cpp: src/IYRruntimeverificationAdaptor_interface.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yerith/yeroth-erp-3-0-system-daemon/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yerith/yeroth-erp-3-0-system-daemon -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/IYRruntimeverificationAdaptor_interface.h -o moc/moc_IYRruntimeverificationAdaptor_interface.cpp

moc/moc_YEROTH_RUNTIME_VERIFIER.cpp: src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yerith/yeroth-erp-3-0-system-daemon/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yerith/yeroth-erp-3-0-system-daemon -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/dbus/YEROTH_RUNTIME_VERIFIER.hpp -o moc/moc_YEROTH_RUNTIME_VERIFIER.cpp

moc/moc_yeroth-erp-3-0-system-daemon-abstract-entity.cpp: src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yerith/yeroth-erp-3-0-system-daemon/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yerith/yeroth-erp-3-0-system-daemon -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp -o moc/moc_yeroth-erp-3-0-system-daemon-abstract-entity.cpp

moc/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp: src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yerith/yeroth-erp-3-0-system-daemon/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yerith/yeroth-erp-3-0-system-daemon -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp -o moc/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp

moc/moc_yeroth-erp-3-0-system-daemon-utils.cpp: src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yerith/yeroth-erp-3-0-system-daemon/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yerith/yeroth-erp-3-0-system-daemon -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/utils/yeroth-erp-3-0-system-daemon-utils.hpp -o moc/moc_yeroth-erp-3-0-system-daemon-utils.cpp

moc/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp: src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yerith/yeroth-erp-3-0-system-daemon/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yerith/yeroth-erp-3-0-system-daemon -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.hpp -o moc/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp

moc/moc_yeroth-erp-3-0-system-daemon-periode.cpp: src/yeroth-erp-3-0-system-daemon-periode.hpp \
		src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yerith/yeroth-erp-3-0-system-daemon/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yerith/yeroth-erp-3-0-system-daemon -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/yeroth-erp-3-0-system-daemon-periode.hpp -o moc/moc_yeroth-erp-3-0-system-daemon-periode.cpp

moc/moc_yeroth-erp-3-0-system-daemon-quantite.cpp: src/yeroth-erp-3-0-system-daemon-quantite.hpp \
		src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		src/include/yeroth-erp-3-0-software-text-configuration.hpp \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yerith/yeroth-erp-3-0-system-daemon/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yerith/yeroth-erp-3-0-system-daemon -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/yeroth-erp-3-0-system-daemon-quantite.hpp -o moc/moc_yeroth-erp-3-0-system-daemon-quantite.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_no_pch_compiler_make_all:
compiler_no_pch_compiler_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/YRruntimeverification_adaptor.o: src/YRruntimeverification_adaptor.cpp src/YRruntimeverification_adaptor.h \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/YRruntimeverification_adaptor.o src/YRruntimeverification_adaptor.cpp

obj/IYRruntimeverificationAdaptor_interface.o: src/IYRruntimeverificationAdaptor_interface.cpp src/IYRruntimeverificationAdaptor_interface.h \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/IYRruntimeverificationAdaptor_interface.o src/IYRruntimeverificationAdaptor_interface.cpp

obj/YEROTH_RUNTIME_VERIFIER.o: src/dbus/YEROTH_RUNTIME_VERIFIER.cpp src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/YEROTH_RUNTIME_VERIFIER.o src/dbus/YEROTH_RUNTIME_VERIFIER.cpp

obj/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.o: src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.cpp src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.o src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.cpp

obj/yeroth-erp-3-0-system-daemon-abstract-entity.o: src/include/yeroth-erp-3-0-system-daemon-abstract-entity.cpp src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-abstract-entity.o src/include/yeroth-erp-3-0-system-daemon-abstract-entity.cpp

obj/yeroth-erp-3-0-system-daemon-alert-abstract-entity.o: src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.hpp \
		src/utils/yeroth-erp-database-table-column.hpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-alert-abstract-entity.o src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp

obj/yeroth-erp-3-0-system-daemon-utils.o: src/utils/yeroth-erp-3-0-system-daemon-utils.cpp src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		src/yeroth-erp-3-0-system-daemon-logger.hpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-utils.o src/utils/yeroth-erp-3-0-system-daemon-utils.cpp

obj/yeroth-erp-3-0-system-daemon.o: src/yeroth-erp-3-0-system-daemon.cpp src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		src/yeroth-erp-3-0-system-daemon-periode.hpp \
		src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp \
		src/yeroth-erp-3-0-system-daemon-quantite.hpp \
		src/include/yeroth-erp-3-0-software-text-configuration.hpp \
		src/yeroth-erp-3-0-system-daemon-config.hpp \
		src/yeroth-erp-3-0-system-daemon-database.hpp \
		src/yeroth-erp-3-0-system-daemon-logger.hpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon.o src/yeroth-erp-3-0-system-daemon.cpp

obj/yeroth-erp-database-table-column.o: src/utils/yeroth-erp-database-table-column.cpp src/utils/yeroth-erp-database-table-column.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-database-table-column.o src/utils/yeroth-erp-database-table-column.cpp

obj/yeroth-erp-3-0-system-daemon-db-backup-export-gz.o: src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		src/yeroth-erp-3-0-system-daemon-config.hpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-db-backup-export-gz.o src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp

obj/yeroth-erp-3-0-system-daemon-periode.o: src/yeroth-erp-3-0-system-daemon-periode.cpp src/yeroth-erp-3-0-system-daemon-periode.hpp \
		src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.hpp \
		src/utils/yeroth-erp-database-table-column.hpp \
		src/yeroth-erp-3-0-system-daemon-logger.hpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-periode.o src/yeroth-erp-3-0-system-daemon-periode.cpp

obj/yeroth-erp-3-0-system-daemon-database.o: src/yeroth-erp-3-0-system-daemon-database.cpp src/yeroth-erp-3-0-system-daemon-database.hpp \
		src/yeroth-erp-3-0-system-daemon-config.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-database.o src/yeroth-erp-3-0-system-daemon-database.cpp

obj/yeroth-erp-3-0-system-daemon-quantite.o: src/yeroth-erp-3-0-system-daemon-quantite.cpp src/yeroth-erp-3-0-system-daemon-quantite.hpp \
		src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp \
		src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		src/include/yeroth-erp-3-0-software-text-configuration.hpp \
		src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.hpp \
		src/yeroth-erp-3-0-system-daemon-logger.hpp \
		src/utils/yeroth-erp-database-table-column.hpp \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-quantite.o src/yeroth-erp-3-0-system-daemon-quantite.cpp

obj/yeroth-erp-3-0-system-daemon-logger.o: src/yeroth-erp-3-0-system-daemon-logger.cpp src/yeroth-erp-3-0-system-daemon-logger.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-logger.o src/yeroth-erp-3-0-system-daemon-logger.cpp

obj/yeroth-erp-3-0-system-daemon-config.o: src/yeroth-erp-3-0-system-daemon-config.cpp src/yeroth-erp-3-0-system-daemon-config.hpp \
		src/utils/yeroth-erp-3-0-system-daemon-utils.hpp \
		src/dbus/YEROTH_RUNTIME_VERIFIER.hpp \
		src/IYRruntimeverificationAdaptor_interface.h \
		obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/yeroth-erp-3-0-system-daemon-config.o src/yeroth-erp-3-0-system-daemon-config.cpp

obj/moc_YRruntimeverification_adaptor.o: moc/moc_YRruntimeverification_adaptor.cpp obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/moc_YRruntimeverification_adaptor.o moc/moc_YRruntimeverification_adaptor.cpp

obj/moc_IYRruntimeverificationAdaptor_interface.o: moc/moc_IYRruntimeverificationAdaptor_interface.cpp obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/moc_IYRruntimeverificationAdaptor_interface.o moc/moc_IYRruntimeverificationAdaptor_interface.cpp

obj/moc_YEROTH_RUNTIME_VERIFIER.o: moc/moc_YEROTH_RUNTIME_VERIFIER.cpp obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/moc_YEROTH_RUNTIME_VERIFIER.o moc/moc_YEROTH_RUNTIME_VERIFIER.cpp

obj/moc_yeroth-erp-3-0-system-daemon-abstract-entity.o: moc/moc_yeroth-erp-3-0-system-daemon-abstract-entity.cpp obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/moc_yeroth-erp-3-0-system-daemon-abstract-entity.o moc/moc_yeroth-erp-3-0-system-daemon-abstract-entity.cpp

obj/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.o: moc/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.o moc/moc_yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp

obj/moc_yeroth-erp-3-0-system-daemon-utils.o: moc/moc_yeroth-erp-3-0-system-daemon-utils.cpp obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/moc_yeroth-erp-3-0-system-daemon-utils.o moc/moc_yeroth-erp-3-0-system-daemon-utils.cpp

obj/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.o: moc/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.o moc/moc_yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp

obj/moc_yeroth-erp-3-0-system-daemon-periode.o: moc/moc_yeroth-erp-3-0-system-daemon-periode.cpp obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/moc_yeroth-erp-3-0-system-daemon-periode.o moc/moc_yeroth-erp-3-0-system-daemon-periode.cpp

obj/moc_yeroth-erp-3-0-system-daemon-quantite.o: moc/moc_yeroth-erp-3-0-system-daemon-quantite.cpp obj/yeroth-erp-3-0-system-daemon.gch/c++
	$(CXX) -c -include obj/yeroth-erp-3-0-system-daemon $(CXXFLAGS) $(INCPATH) -o obj/moc_yeroth-erp-3-0-system-daemon-quantite.o moc/moc_yeroth-erp-3-0-system-daemon-quantite.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/yeroth-erp-3-0-system-daemon-3.0 || mkdir -p $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/yeroth-erp-3-0-system-daemon-3.0
	$(QINSTALL_PROGRAM) bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/yeroth-erp-3-0-system-daemon-3.0/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/yeroth-erp-3-0-system-daemon-3.0/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/yeroth-erp-3-0-system-daemon-3.0/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/yeroth-erp-3-0-system-daemon-3.0/ 


install_sources: first FORCE
	@test -d $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/. || mkdir -p $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/.
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/YRruntimeverification_adaptor.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./YRruntimeverification_adaptor.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/IYRruntimeverificationAdaptor_interface.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./IYRruntimeverificationAdaptor_interface.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/dbus/YEROTH_RUNTIME_VERIFIER.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./YEROTH_RUNTIME_VERIFIER.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/include/yeroth-erp-3-0-system-daemon-abstract-entity.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-abstract-entity.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/utils/yeroth-erp-3-0-system-daemon-utils.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-utils.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/utils/yeroth-erp-database-table-column.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-database-table-column.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-periode.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-periode.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-database.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-database.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-quantite.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-quantite.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-logger.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-logger.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-config.cpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-config.cpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/YRruntimeverification_adaptor.h $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./YRruntimeverification_adaptor.h
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/IYRruntimeverificationAdaptor_interface.h $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./IYRruntimeverificationAdaptor_interface.h
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/dbus/YEROTH_RUNTIME_VERIFIER.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./YEROTH_RUNTIME_VERIFIER.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/entities/yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/include/yeroth-erp-3-0-system-daemon-abstract-entity.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-abstract-entity.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/include/yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/include/yeroth-erp-3-0-definition-oo-class-operators.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-definition-oo-class-operators.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/include/yeroth-erp-3-0-software-text-configuration.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-software-text-configuration.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/utils/yeroth-erp-3-0-system-daemon-utils.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-utils.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/utils/yeroth-erp-database-table-column.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-database-table-column.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-db-backup-export-gz.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-db-backup-export-gz.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-periode.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-periode.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-database.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-database.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-quantite.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-quantite.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-logger.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-logger.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/src/yeroth-erp-3-0-system-daemon-config.hpp $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-config.hpp
	$(QINSTALL) /home/yerith/yeroth-erp-3-0-system-daemon/yeroth-erp-3-0-system-daemon.pro $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon.pro

uninstall_sources: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon.pro
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-config.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-logger.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-quantite.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-database.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-periode.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-db-backup-export-gz.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-database-table-column.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-utils.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-software-text-configuration.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-definition-oo-class-operators.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-alert-abstract-entity.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-abstract-entity.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./YEROTH_RUNTIME_VERIFIER.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./IYRruntimeverificationAdaptor_interface.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./YRruntimeverification_adaptor.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-config.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-logger.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-quantite.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-database.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-periode.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-db-backup-export-gz.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-database-table-column.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-utils.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-alert-abstract-entity.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-abstract-entity.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./yeroth-erp-3-0-system-daemon-entity-alert-quantity-period-time.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./YEROTH_RUNTIME_VERIFIER.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./IYRruntimeverificationAdaptor_interface.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./YRruntimeverification_adaptor.cpp
	-$(DEL_DIR) $(INSTALL_ROOT)/home/yerith/yeroth-erp-3-0-system-daemon/./ 


install: install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources  FORCE

FORCE:

