/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c IYRruntimeverificationAdaptor_Interface -p src/IYRruntimeverificationAdaptor_interface.h:src/IYRruntimeverificationAdaptor_interface.cpp src/dbus/yr.db-runtime.verif.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "src/IYRruntimeverificationAdaptor_interface.h"

/*
 * Implementation of interface class IYRruntimeverificationAdaptor_Interface
 */

IYRruntimeverificationAdaptor_Interface::IYRruntimeverificationAdaptor_Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

IYRruntimeverificationAdaptor_Interface::~IYRruntimeverificationAdaptor_Interface()
{
}

